[versions]
kotlin = "1.7.20"

[libraries]
jetbrains-kotlin = { module = "org.jetbrains.kotlin:kotlin-stdlib-jdk7", version.ref = "kotlin" }
kotlinutils = 'com.github.w2sv:KotlinUtils:0.0.5'
viewboundcontroller = 'com.github.w2sv:ViewboundController:0.0.7-rc1'
androidutils = 'com.github.w2sv:AndroidUtils:0.0.7'
typedpreferences = 'com.github.w2sv:TypedPreferences:1.0.0'

androidx-appcompat = 'androidx.appcompat:appcompat:1.5.1'
androidx-core = 'androidx.core:core-ktx:1.9.0'
androidx-viewpager2 = 'androidx.viewpager2:viewpager2:1.0.0'
androidx-viewmodel = 'androidx.lifecycle:lifecycle-viewmodel-ktx:2.6.0-alpha03'
androidx-fragment = 'androidx.fragment:fragment-ktx:1.6.0-alpha03'
androidx-activity = 'androidx.activity:activity-ktx:1.7.0-alpha02'
androidx-splashscreen = 'androidx.core:core-splashscreen:1.0.0'

google-guava = 'com.google.guava:guava:31.1-jre'
google-material = 'com.google.android.material:material:1.7.0'
google-hilt = 'com.google.dagger:hilt-android:2.44.2'
google-hilt-kapt = 'com.google.dagger:hilt-android-compiler:2.44.2'

slimber = 'com.github.PaulWoitaschek:Slimber:2.0.0'
snacky = 'com.github.matecode:Snacky:1.1.5'
animatoo = 'com.github.mohammadatif:Animatoo:master'
viewanimations = 'com.github.w2sv:AndroidViewAnimations:master-SNAPSHOT'

# unitTest
junit5 = 'org.junit.jupiter:junit-jupiter:5.9.1'
androidx-junit = 'androidx.test.ext:junit:1.1.4'

# androidTest
androidx-testrunner = 'androidx.test:runner:1.5.1'
junit5-api = 'org.junit.jupiter:junit-jupiter-api:5.9.1'
junit5-mannodermaus-core = 'de.mannodermaus.junit5:android-test-core:1.3.0'
junit5-mannodermaus-runner = 'de.mannodermaus.junit5:android-test-runner:1.3.0'
junit5-params = 'org.junit.jupiter:junit-jupiter-params:5.9.1'

# .Espresso
androidx-espresso-core = 'androidx.test.espresso:espresso-core:3.5.0'
androidx-espresso-intents = 'androidx.test.espresso:espresso-intents:3.5.0'

[bundles]
unitTest = ["junit5", "androidx-junit"]
androidTest = ["androidx-testrunner", "junit5-api", "junit5-mannodermaus-core", "junit5-mannodermaus-runner"]
