[versions]
kotlin = '1.8.0'
hilt = '2.44.2'
junit = '5.9.2'
mannodermaus = '1.3.0'
espresso = '3.5.1'

[libraries]
jetbrains-kotlin = { module = 'org.jetbrains.kotlin:kotlin-stdlib-jdk7', version.ref = 'kotlin' }

# owned
kotlinutils = 'com.github.w2sv:KotlinUtils:0.0.6-rc2'
viewboundcontroller = 'com.github.w2sv:ViewboundController:0.0.7-rc1'
androidutils = 'com.github.w2sv:AndroidUtils:0.0.13'
typedpreferences = 'com.github.w2sv:TypedPreferences:1.0.0'
viewanimations = 'com.github.w2sv:AndroidViewAnimations:3.0.2-rc2'
onboarder = 'com.github.w2sv:AndroidOnboarder:0.0.2-rc3'
permissionhandler = 'com.github.w2sv:PermissionHandler:1.0.0-rc1'

# androidx
androidx-appcompat = 'androidx.appcompat:appcompat:1.7.0-alpha01'
androidx-core = 'androidx.core:core-ktx:1.10.0-alpha01'
androidx-viewpager2 = 'androidx.viewpager2:viewpager2:1.1.0-beta01'
androidx-viewmodel = 'androidx.lifecycle:lifecycle-viewmodel-ktx:2.6.0-alpha05'  # alpha04 causing buggy AS error notifications
androidx-fragment = 'androidx.fragment:fragment-ktx:1.6.0-alpha04'
androidx-activity = 'androidx.activity:activity-ktx:1.7.0-alpha03'
androidx-splashscreen = 'androidx.core:core-splashscreen:1.0.0'

# google
google-guava = 'com.google.guava:guava:31.1-jre'
google-material = 'com.google.android.material:material:1.7.0'
google-hilt = { module = 'com.google.dagger:hilt-android', version.ref = 'hilt' }
google-hilt-kapt = { module = 'com.google.dagger:hilt-android-compiler', version.ref = 'hilt' }

# other
slimber = 'com.github.PaulWoitaschek:Slimber:2.0.0'
snacky = 'com.github.matecode:Snacky:1.1.5'
animatoo = 'com.github.mohammadatif:Animatoo:master'
lottie = 'com.airbnb.android:lottie:5.2.0'

## unitTest
junit5 = { module = 'org.junit.jupiter:junit-jupiter', version.ref = 'junit' }
androidx-junit = 'androidx.test.ext:junit:1.1.5'

## androidTest
androidx-testrunner = 'androidx.test:runner:1.5.1'
junit5-api = { module = 'org.junit.jupiter:junit-jupiter-api', version.ref = 'junit' }
junit5-params = { module = 'org.junit.jupiter:junit-jupiter-params', version.ref = 'junit' }
junit5-mannodermaus-core = { module = 'de.mannodermaus.junit5:android-test-core', version.ref = 'mannodermaus' }
junit5-mannodermaus-runner = { module = 'de.mannodermaus.junit5:android-test-runner', version.ref = 'mannodermaus' }

# espresso
androidx-espresso-core = { module = 'androidx.test.espresso:espresso-core', version.ref = 'espresso' }
androidx-espresso-intents = { module = 'androidx.test.espresso:espresso-intents', version.ref = 'espresso' }

[bundles]
unitTest = ["junit5", "androidx-junit"]
androidTest = ["androidx-testrunner", "junit5-api", "junit5-mannodermaus-core", "junit5-mannodermaus-runner"]
