[versions]
kotlin = '1.8.0'
hilt = '2.44.2'

[libraries]
jetbrains-kotlin = { module = 'org.jetbrains.kotlin:kotlin-stdlib-jdk7', version.ref = 'kotlin' }

# owned
kotlinutils = 'com.github.w2sv:KotlinUtils:0.0.5'
viewboundcontroller = 'com.github.w2sv:ViewboundController:0.0.7-rc1'
androidutils = 'com.github.w2sv:AndroidUtils:0.0.10-rc1'
typedpreferences = 'com.github.w2sv:TypedPreferences:1.0.0'
viewanimations = 'com.github.w2sv:AndroidViewAnimations:3.0.0'

# androidx
androidx-appcompat = 'androidx.appcompat:appcompat:1.5.1'
androidx-core = 'androidx.core:core-ktx:1.9.0'
androidx-viewpager2 = 'androidx.viewpager2:viewpager2:1.0.0'
androidx-viewmodel = 'androidx.lifecycle:lifecycle-viewmodel-ktx:2.6.0-alpha03'
androidx-fragment = 'androidx.fragment:fragment-ktx:1.6.0-alpha04'
androidx-activity = 'androidx.activity:activity-ktx:1.7.0-alpha02'
androidx-splashscreen = 'androidx.core:core-splashscreen:1.0.0'

# google
google-guava = 'com.google.guava:guava:31.1-jre'
google-material = 'com.google.android.material:material:1.7.0'
google-hilt = { module = 'com.google.dagger:hilt-android', version.ref = 'hilt' }
google-hilt-kapt = { module = 'com.google.dagger:hilt-android-compiler', version.ref = 'hilt' }

# other
slimber = 'com.github.PaulWoitaschek:Slimber:2.0.0'
snacky = 'com.github.matecode:Snacky:1.1.5'
animatoo = 'com.github.mohammadatif:Animatoo:master'
lottie = 'com.airbnb.android:lottie:5.2.0'
paperonboarding = 'com.ramotion.paperonboarding:paper-onboarding:1.1.3'

## unitTest
junit5 = 'org.junit.jupiter:junit-jupiter:5.9.1'
androidx-junit = 'androidx.test.ext:junit:1.1.5'

## androidTest
androidx-testrunner = 'androidx.test:runner:1.5.1'
junit5-api = 'org.junit.jupiter:junit-jupiter-api:5.9.1'
junit5-mannodermaus-core = 'de.mannodermaus.junit5:android-test-core:1.3.0'
junit5-mannodermaus-runner = 'de.mannodermaus.junit5:android-test-runner:1.3.0'
junit5-params = 'org.junit.jupiter:junit-jupiter-params:5.9.1'

# espresso
androidx-espresso-core = 'androidx.test.espresso:espresso-core:3.5.1'
androidx-espresso-intents = 'androidx.test.espresso:espresso-intents:3.5.1'

[bundles]
unitTest = ["junit5", "androidx-junit"]
androidTest = ["androidx-testrunner", "junit5-api", "junit5-mannodermaus-core", "junit5-mannodermaus-runner"]
