package com.autocrop.screencapturelistening.notification

const val ASSOCIATED_NOTIFICATION_ID = "ASSOCIATED_NOTIFICATION_ID"
const val CANCEL_NOTIFICATION_ACTION = "com.w2sv.autocrop.CANCEL_NOTIFICATION_ACTION"
const val ASSOCIATED_PENDING_REQUEST_CODES = "ASSOCIATED_PENDING_REQUEST_CODES"