package com.w2sv.autocrop.ui.theme

import androidx.compose.material3.ColorScheme
import androidx.compose.runtime.Composable
import androidx.compose.runtime.ReadOnlyComposable
import androidx.compose.ui.graphics.Color

val ColorScheme.onSurfaceVariantLowAlpha: Color
    @Composable
    @ReadOnlyComposable
    get() = onSurfaceVariant.copy(0.6f)

val Seed = Color(0xFF7F1F3F)

val PrimaryLightReducedContrast = Color(0xFF9D3756)
val OnPrimaryLightReducedContrast = Color(0xFFFFEFF0)
val PrimaryContainerLightReducedContrast = Color(0xFFFA7F9F)
val OnPrimaryContainerLightReducedContrast = Color(0xFF560023)
val InversePrimaryLightReducedContrast = Color(0xFFE06B8A)
val SecondaryLightReducedContrast = Color(0xFF99366E)
val OnSecondaryLightReducedContrast = Color(0xFFFFEFF3)
val SecondaryContainerLightReducedContrast = Color(0xFFFFC0DC)
val OnSecondaryContainerLightReducedContrast = Color(0xFF7F2159)
val TertiaryLightReducedContrast = Color(0xFF5C4BB4)
val OnTertiaryLightReducedContrast = Color(0xFFF6F0FF)
val TertiaryContainerLightReducedContrast = Color(0xFFB2A5FF)
val OnTertiaryContainerLightReducedContrast = Color(0xFF301887)
val BackgroundLightReducedContrast = Color(0xFFFFF4F6)
val OnBackgroundLightReducedContrast = Color(0xFF492136)
val SurfaceLightReducedContrast = Color(0xFFFFF4F6)
val OnSurfaceLightReducedContrast = Color(0xFF492136)
val SurfaceVariantLightReducedContrast = Color(0xFFFFD0E4)
val OnSurfaceVariantLightReducedContrast = Color(0xFF7C4D64)
val SurfaceTintLightReducedContrast = Color(0xFF9D3756)
val InverseSurfaceLightReducedContrast = Color(0xFF220215)
val InverseOnSurfaceLightReducedContrast = Color(0xFFC48DA6)
val ErrorLightReducedContrast = Color(0xFFB31B25)
val OnErrorLightReducedContrast = Color(0xFFFFEFEE)
val ErrorContainerLightReducedContrast = Color(0xFFFB5151)
val OnErrorContainerLightReducedContrast = Color(0xFF570008)
val OutlineLightReducedContrast = Color(0xFF9B6880)
val OutlineVariantLightReducedContrast = Color(0xFFE197BA)
val ScrimLightReducedContrast = Color(0xFF000000)
val SurfaceBrightLightReducedContrast = Color(0xFFFFF4F6)
val SurfaceContainerLightReducedContrast = Color(0xFFFFE0EC)
val SurfaceContainerHighLightReducedContrast = Color(0xFFFFD8E8)
val SurfaceContainerHighestLightReducedContrast = Color(0xFFFFD0E4)
val SurfaceContainerLowLightReducedContrast = Color(0xFFFFECF2)
val SurfaceContainerLowestLightReducedContrast = Color(0xFFFFFFFF)
val SurfaceDimLightReducedContrast = Color(0xFFFFC4DE)

val PrimaryDarkReducedContrast = Color(0xFFF07897)
val OnPrimaryDarkReducedContrast = Color(0xFF48001C)
val PrimaryContainerDarkReducedContrast = Color(0xFFF37A9A)
val OnPrimaryContainerDarkReducedContrast = Color(0xFF4C001E)
val InversePrimaryDarkReducedContrast = Color(0xFFA23A59)
val SecondaryDarkReducedContrast = Color(0xFFE978B3)
val OnSecondaryDarkReducedContrast = Color(0xFF45002D)
val SecondaryContainerDarkReducedContrast = Color(0xFF7F2059)
val OnSecondaryContainerDarkReducedContrast = Color(0xFFFFBEDB)
val TertiaryDarkReducedContrast = Color(0xFF9F8FFD)
val OnTertiaryDarkReducedContrast = Color(0xFF1F006F)
val TertiaryContainerDarkReducedContrast = Color(0xFF9F8FFD)
val OnTertiaryContainerDarkReducedContrast = Color(0xFF1F006F)
val BackgroundDarkReducedContrast = Color(0xFF220215)
val OnBackgroundDarkReducedContrast = Color(0xFFFFDCEA)
val SurfaceDarkReducedContrast = Color(0xFF220215)
val OnSurfaceDarkReducedContrast = Color(0xFFFFDCEA)
val SurfaceVariantDarkReducedContrast = Color(0xFF451230)
val OnSurfaceVariantDarkReducedContrast = Color(0xFFBA849D)
val SurfaceTintDarkReducedContrast = Color(0xFFF07897)
val InverseSurfaceDarkReducedContrast = Color(0xFFFFF8F8)
val InverseOnSurfaceDarkReducedContrast = Color(0xFF75475D)
val ErrorDarkReducedContrast = Color(0xFFFF716C)
val OnErrorDarkReducedContrast = Color(0xFF490006)
val ErrorContainerDarkReducedContrast = Color(0xFF9F0519)
val OnErrorContainerDarkReducedContrast = Color(0xFFFFA8A3)
val OutlineDarkReducedContrast = Color(0xFF99667E)
val OutlineVariantDarkReducedContrast = Color(0xFF6E3453)
val ScrimDarkReducedContrast = Color(0xFF000000)
val SurfaceBrightDarkReducedContrast = Color(0xFF4E1737)
val SurfaceContainerDarkReducedContrast = Color(0xFF330822)
val SurfaceContainerHighDarkReducedContrast = Color(0xFF3C0D29)
val SurfaceContainerHighestDarkReducedContrast = Color(0xFF451230)
val SurfaceContainerLowDarkReducedContrast = Color(0xFF2A041B)
val SurfaceContainerLowestDarkReducedContrast = Color(0xFF000000)
val SurfaceDimDarkReducedContrast = Color(0xFF220215)

val PrimaryFixedReducedContrast = Color(0xFFFA7F9F)
val PrimaryFixedDimReducedContrast = Color(0xFFE97292)
val OnPrimaryFixedReducedContrast = Color(0xFF160005)
val OnPrimaryFixedVariantReducedContrast = Color(0xFF64062C)
val SecondaryFixedReducedContrast = Color(0xFFFFC0DC)
val SecondaryFixedDimReducedContrast = Color(0xFFFFABD3)
val OnSecondaryFixedReducedContrast = Color(0xFF660845)
val OnSecondaryFixedVariantReducedContrast = Color(0xFF8B2B63)
val TertiaryFixedReducedContrast = Color(0xFFB2A5FF)
val TertiaryFixedDimReducedContrast = Color(0xFFA595FF)
val OnTertiaryFixedReducedContrast = Color(0xFF170059)
val OnTertiaryFixedVariantReducedContrast = Color(0xFF392490)
