package com.autocrop.screencapturelistening

const val ASSOCIATED_NOTIFICATION_ID = "ASSOCIATED_NOTIFICATION_ID"
const val CANCEL_NOTIFICATION = "CANCEL_NOTIFICATION"
const val ASSOCIATED_PENDING_REQUEST_CODES = "ASSOCIATED_PENDING_REQUEST_CODES"