# References:
#   https://www.raywenderlich.com/10562143-continuous-integration-for-android
#   https://dev.to/ychescale9/running-android-emulators-on-ci-from-bitrise-io-to-github-actions-3j76

name: CI Workflow
on: [push, pull_request]

jobs:
  build-and-test:
    name: Build and run tests
    runs-on: macos-latest  # allows for hardware acceleration through HAXM
    strategy:
      fail-fast: false  # continue if one strategy fails
      matrix:  # @https://docs.github.com/en/actions/using-jobs/using-a-build-matrix-for-your-jobs
        device-profile: [  # paired value syntax: @https://stackoverflow.com/a/68940067/12083276
          { api: 28, device: Nexus 6 },
          { api: 29, device: Nexus 6 },
          { api: 30, device: Nexus 6 },
          { api: 31, device: Nexus 6 }
        ]
    steps:
      - name: Checkout current repository in ubuntu's file system
        uses: actions/checkout@v2

      - name: Setup JDK
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Gradle cache
        uses: gradle/gradle-build-action@v2

      - name: AVD cache
        uses: actions/cache@v3
        id: avd-cache
        with:
          path: |
            ~/.android/avd/*
            ~/.android/adb*
          key: avd-${{ matrix.device-profile.api }}

      - name: create AVD and generate snapshot for caching
        if: steps.avd-cache.outputs.cache-hit != 'true'
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.device-profile.api }}
          profile: ${{ matrix.device-profile.device }}
          arch: x86_64
          force-avd-creation: false
          emulator-options: -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          disable-animations: true
          script: echo "Generated AVD snapshot for caching."

      - name: Run Unit tests
        run: |
          chmod +x gradlew
          ./gradlew testDebugUnitTest

      - name: Run Instrumentation tests
        uses: reactivecircus/android-emulator-runner@v2  # @https://github.com/ReactiveCircus/android-emulator-runner
        with:
          api-level: ${{ matrix.device-profile.api }}
          profile: ${{ matrix.device-profile.device }}
          arch: x86_64
          force-avd-creation: false
          emulator-options: -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none -no-snapshot
          disable-animations: true
          script: ./gradlew connectedCheck

      - name: Upload Reports
        uses: actions/upload-artifact@v1
        with:
          name: reports
          path: app/build/reports