# Reference: https://www.raywenderlich.com/10562143-continuous-integration-for-android
# https://dev.to/ychescale9/running-android-emulators-on-ci-from-bitrise-io-to-github-actions-3j76

name: CI Workflow
on: [push, pull_request]

jobs:
  build-and-test:
    name: Build and run tests
    runs-on: macos-latest  # allows for hardware acceleration through HAXM
    steps:
      - name: Checkout current repository in ubuntu's file system
        uses: actions/checkout@v2

      - name: Setup JDK
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Unit tests
        run: |
          chmod +x gradlew
          ./gradlew testDebugUnitTest

      - name: Instrumentation tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          arch: x86
          profile: Nexus 6
          avd-name: test
          emulator-options: -no-window -gpu swiftshader_indirect -no-snapshot -noaudio -no-boot-anim -camera-back none
          disable-animations: true
          script: ./gradlew connectedCheck

      - name: Upload Reports
        uses: actions/upload-artifact@v1
        with:
          name: reports
          path: app/build/reports